name: Doxygen Documentation Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt update && sudo apt install -y doxygen graphviz cmake

      - name: Configure project with CMake
        run: cmake -S . -B build

      - name: Generate Doxygen Documentation
        run: cmake --build build --target doc

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Doxygen Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/doxygen/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
